# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sokoban/sokoban.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban || ORIG_REF_NAME==sokoban} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_axi_gpio_0_0/sokoban_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_axi_gpio_0_0 || ORIG_REF_NAME==sokoban_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_axi_gpio_1_0/sokoban_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_axi_gpio_1_0 || ORIG_REF_NAME==sokoban_axi_gpio_1_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_processing_system7_0_0/sokoban_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_processing_system7_0_0 || ORIG_REF_NAME==sokoban_processing_system7_0_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_ps7_0_axi_periph_0/sokoban_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_ps7_0_axi_periph_0 || ORIG_REF_NAME==sokoban_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_rst_ps7_0_50M_0/sokoban_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_rst_ps7_0_50M_0 || ORIG_REF_NAME==sokoban_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_xbar_0/sokoban_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_xbar_0 || ORIG_REF_NAME==sokoban_xbar_0} -quiet] -quiet

# IP: bd/sokoban/ip/sokoban_auto_pc_0/sokoban_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sokoban_auto_pc_0 || ORIG_REF_NAME==sokoban_auto_pc_0} -quiet] -quiet

# XDC: bd/sokoban/sokoban_ooc.xdc
