# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uart_test1/uart_test1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1 || ORIG_REF_NAME==uart_test1} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_processing_system7_0_0/uart_test1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_processing_system7_0_0 || ORIG_REF_NAME==uart_test1_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_ps7_0_axi_periph_0/uart_test1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_test1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_rst_ps7_0_50M_0/uart_test1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_rst_ps7_0_50M_0 || ORIG_REF_NAME==uart_test1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_xbar_0/uart_test1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_xbar_0 || ORIG_REF_NAME==uart_test1_xbar_0} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_axi_gpio_0_1/uart_test1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_axi_gpio_0_1 || ORIG_REF_NAME==uart_test1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_axi_gpio_1_1/uart_test1_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_axi_gpio_1_1 || ORIG_REF_NAME==uart_test1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/uart_test1/ip/uart_test1_auto_pc_0/uart_test1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_test1_auto_pc_0 || ORIG_REF_NAME==uart_test1_auto_pc_0} -quiet] -quiet

# XDC: bd/uart_test1/uart_test1_ooc.xdc
