# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/interrupt/interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt || ORIG_REF_NAME==interrupt} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_processing_system7_0_1/interrupt_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_processing_system7_0_1 || ORIG_REF_NAME==interrupt_processing_system7_0_1} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_axi_gpio_0_2/interrupt_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_0_2 || ORIG_REF_NAME==interrupt_axi_gpio_0_2} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_axi_gpio_1_1/interrupt_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_1_1 || ORIG_REF_NAME==interrupt_axi_gpio_1_1} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_ps7_0_axi_periph_0/interrupt_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_ps7_0_axi_periph_0 || ORIG_REF_NAME==interrupt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_rst_ps7_0_50M_0/interrupt_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==interrupt_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_xbar_0 || ORIG_REF_NAME==interrupt_xbar_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_auto_pc_0/interrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_auto_pc_0 || ORIG_REF_NAME==interrupt_auto_pc_0} -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_processing_system7_0_1/interrupt_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_processing_system7_0_1 || ORIG_REF_NAME==interrupt_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_axi_gpio_0_2/interrupt_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_0_2 || ORIG_REF_NAME==interrupt_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_axi_gpio_0_2/interrupt_axi_gpio_0_2_ooc.xdc

# XDC: bd/interrupt/ip/interrupt_axi_gpio_0_2/interrupt_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_0_2 || ORIG_REF_NAME==interrupt_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_axi_gpio_1_1/interrupt_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_1_1 || ORIG_REF_NAME==interrupt_axi_gpio_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_axi_gpio_1_1/interrupt_axi_gpio_1_1_ooc.xdc

# XDC: bd/interrupt/ip/interrupt_axi_gpio_1_1/interrupt_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_1_1 || ORIG_REF_NAME==interrupt_axi_gpio_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_rst_ps7_0_50M_0/interrupt_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==interrupt_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_rst_ps7_0_50M_0/interrupt_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==interrupt_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt/ip/interrupt_auto_pc_0/interrupt_auto_pc_0_ooc.xdc

# XDC: bd/interrupt/interrupt_ooc.xdc
