# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/Sokoban_Game_sdk/Sokoban_Game/Sokoban_Game.srcs/sources_1/bd/sokoban/ip/sokoban_xbar_0/sokoban_xbar_0.xci
# IP: The module: 'sokoban_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/Sokoban_Game_sdk/Sokoban_Game/Sokoban_Game.srcs/sources_1/bd/sokoban/ip/sokoban_xbar_0/sokoban_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sokoban_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/Sokoban_Game_sdk/Sokoban_Game/Sokoban_Game.srcs/sources_1/bd/sokoban/ip/sokoban_xbar_0/sokoban_xbar_0.xci
# IP: The module: 'sokoban_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/Sokoban_Game_sdk/Sokoban_Game/Sokoban_Game.srcs/sources_1/bd/sokoban/ip/sokoban_xbar_0/sokoban_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sokoban_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
