# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/test/sdk/uart_test1/uart_test1.srcs/sources_1/bd/uart_test1/ip/uart_test1_xbar_0/uart_test1_xbar_0.xci
# IP: The module: 'uart_test1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/test/sdk/uart_test1/uart_test1.srcs/sources_1/bd/uart_test1/ip/uart_test1_xbar_0/uart_test1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_test1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/test/sdk/uart_test1/uart_test1.srcs/sources_1/bd/uart_test1/ip/uart_test1_xbar_0/uart_test1_xbar_0.xci
# IP: The module: 'uart_test1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jason/Desktop/verilog_lab/soc_work/final_project/Code/test/sdk/uart_test1/uart_test1.srcs/sources_1/bd/uart_test1/ip/uart_test1_xbar_0/uart_test1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_test1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
